version: 0.2

phases:
    runtime-versions: 
        node.js: 12.14.1
    install:    
        commands:
            - npm install -g @angular/cli
            - npm install
    pre_build:
        commands:
            # npm run test
            # npm run e2e                    
    build:
        commands:
            - ng build --prod
    post_build:
         commands:
            - aws s3 sync --delete ./dist/angular-ff s3://fantasy-football-2019.chrisyou.com
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/*'
    discard-paths: yes
    
    

phases:
  install:
    runtime-versions:
        php: 7.3
  build:
    commands:
      - php --version
artifacts:
  files:
    -  README.md