version: 0.2
env:
  variables:    
    WWW_S3_BUCKET: "www.stock.chrisyou.com"
phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod  --aot
    post_build:
        commands:
            - aws s3 sync --delete ./dist/Stock-Web-App s3://${WWW_S3_BUCKET}
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/*'
    discard-paths: yes
    